<connect_BLE_Screen>:
    cols: 2
    Connections_Label: Connections_Label
    Label:
        row: 0
        col: 0
        text: "BLE Connection Screen"
    Button:
        row: 0
        col: 1
        text: "Scan for Devices"
        on_press: root.Scan_Button_Pressed()

    Label:
        row: 1
        col: 0
        text:"Connections"
    Label:
        row: 1
        col: 1
        id: "Connections_Label"
        text: "No Devices Connected"