<ConnectBLEScreen>:
    GridLayout:
        cols: 2
        rows: 2
        row_force_default: True
        row_default_height: 50

        Label:
            text: "BLE Connection Screen"
            size_hint_x: None
            width: 200

        Button:
            text: "Scan for Devices"
            on_press: root.scan_button_pressed()
            size_hint_x: None
            width: 200

        Label:
            text: "Available Devices"
            size_hint_x: None
            width: 200

        Label:
            id: connections_label
            text: "No Devices Connected"
            size_hint_x: None
            width: 200